version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: chistyakovn/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media

  frontend:
    image: chistyakovn/foodgram_frontend
    volumes:
      - static:/app/result_build/build/

  nginx:
    image: chistyakovn/foodgram_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles/ 
      - media:/app/media/
      - ./nginx.conf:/etc/nginx/conf_d/default.conf
